import React, { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';

const cx=(...v)=>v.filter(Boolean).join(' ');
const detail=(value)=>({detail:{value}});
export const IonApp=({children,className=''})=><div className={cx('ui-app',className)}>{children}</div>;
export const IonPage=({children,className=''})=><section className={cx('ui-page',className)}>{children}</section>;
export const IonHeader=({children,className=''})=><header className={cx('ui-header',className)}>{children}</header>;
export const IonFooter=({children,className=''})=><footer className={cx('ui-footer',className)}>{children}</footer>;
export const IonToolbar=({children,className=''})=><div className={cx('ui-toolbar',className)}>{children}</div>;
export const IonTitle=({children,className='',...p})=><div className={cx('ui-title',className)} {...p}>{children}</div>;
export const IonButtons=({children,slot,className=''})=><div className={cx('ui-buttons',slot==='end'?'ui-buttons-end':'',className)}>{children}</div>;
export const IonButton=({children,fill,color,expand,className='',...p})=><button className={cx('ui-button',fill&&'ui-button-'+fill,color&&'ui-button-'+color,expand==='block'&&'ui-button-block',className)} {...p}>{children}</button>;
export const IonBadge=({children,className=''})=><span className={cx('ui-badge',className)}>{children}</span>;
export const IonAvatar=({children,className=''})=><span className={cx('ui-avatar',className)}>{children}</span>;
export const IonLabel=({children,className=''})=><div className={cx('ui-label',className)}>{children}</div>;
export const IonList=({children,className=''})=><div className={cx('ui-list',className)}>{children}</div>;
export const IonItem=({children,button,onClick,className='',...p})=>button?<button type="button" className={cx('ui-item','ui-item-button',className)} onClick={onClick}>{children}</button>:<div className={cx('ui-item',className)} onClick={onClick}>{children}</div>;
export const IonItemSliding=({children,className=''})=><div className={cx('ui-item-sliding',className)}>{children}</div>;
export const IonItemOptions=({children})=><div className="ui-item-options">{children}</div>;
export const IonItemOption=({children,onClick})=><button type="button" className="ui-item-option" onClick={onClick}>{children}</button>;
export const IonContent=forwardRef(function IonContent({children,className='',fullscreen,...p},ref){const el=useRef(null);useImperativeHandle(ref,()=>({getScrollElement:async()=>el.current,scrollToBottom:(ms=0)=>el.current?.scrollTo({top:el.current.scrollHeight,behavior:ms?'smooth':'auto'})}));return <main ref={el} className={cx('ui-content',className)} {...p}>{children}</main>});
export const IonSearchbar=forwardRef(function IonSearchbar({value='',placeholder='',onIonInput,className=''},ref){const input=useRef(null);useImperativeHandle(ref,()=>({setFocus:()=>input.current?.focus()}));return <div className={cx('ui-search',className)}><input ref={input} value={value??''} placeholder={placeholder} onChange={e=>onIonInput?.(detail(e.target.value))}/></div>});
export const IonInput=({label,value='',type='text',onIonInput,className=''})=><label className={cx('ui-field',className)}>{label&&<span>{label}</span>}<input type={type} value={value??''} onChange={e=>onIonInput?.(detail(e.target.value))}/></label>;
export const IonTextarea=forwardRef(function IonTextarea({value='',placeholder='',onIonInput,onKeyDown,className='',...p},ref){return <textarea ref={ref} className={cx('ui-textarea',className)} value={value??''} placeholder={placeholder} onChange={e=>onIonInput?.(detail(e.target.value))} onKeyDown={onKeyDown} {...p}/>});
export const IonToggle=({children,checked,onIonChange})=><label className="ui-toggle"><span>{children}</span><input type="checkbox" checked={!!checked} onChange={e=>onIonChange?.({detail:{checked:e.target.checked}})}/><i/></label>;
export const IonSelect=({children,label,value,onIonChange})=><label className="ui-field">{label&&<span>{label}</span>}<select value={value??''} onChange={e=>onIonChange?.(detail(e.target.value))}>{children}</select></label>;
export const IonSelectOption=({children,value})=><option value={value}>{children}</option>;
export const IonSegment=({children,value,onIonChange,className=''})=><div className={cx('ui-segment',className)}>{React.Children.map(children,c=>React.isValidElement(c)?React.cloneElement(c,{active:c.props.value===value,onSelect:v=>onIonChange?.(detail(v))}):c)}</div>;
export const IonSegmentButton=({children,value,active,onSelect})=><button type="button" className={cx('ui-segment-button',active&&'active')} onClick={()=>onSelect?.(value)}>{children}</button>;
export const IonProgressBar=({value=0})=><div className="ui-progress"><i style={{width:`${Math.max(0,Math.min(1,value))*100}%`}}/></div>;
export const IonRefresher=({children})=><>{children}</>; export const IonRefresherContent=()=>null;
export const IonModal=({children,isOpen,onDidDismiss,cssClass=''})=>!isOpen?null:<div className={cx('ui-overlay',cssClass)} role="dialog" aria-modal="true" onMouseDown={e=>{if(e.target===e.currentTarget)onDidDismiss?.()}}><div className="ui-modal">{children}</div></div>;
export const IonToast=({isOpen,message,duration=2500,onDidDismiss})=>{useEffect(()=>{if(!isOpen)return;const t=setTimeout(()=>onDidDismiss?.(),duration);return()=>clearTimeout(t)},[isOpen,duration,onDidDismiss]);return isOpen?<div className="ui-toast" role="status">{message}</div>:null};
export const IonLoading=({isOpen,message})=>isOpen?<div className="ui-overlay ui-loading"><div className="ui-loading-card"><span className="ui-spinner"/>{message}</div></div>:null;
export const IonAlert=({isOpen,header,message,buttons=[],onDidDismiss})=>!isOpen?null:<div className="ui-overlay" role="alertdialog"><div className="ui-dialog"><h3>{header}</h3>{message&&<p>{message}</p>}<div>{buttons.map((b,i)=><button key={i} type="button" className={b.role==='destructive'?'danger':''} onClick={()=>{b.handler?.();onDidDismiss?.()}}>{b.text||b}</button>)}</div></div></div>;
export const IonActionSheet=({isOpen,header,buttons=[],onDidDismiss})=>!isOpen?null:<div className="ui-overlay ui-sheet-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onDidDismiss?.()}}><div className="ui-sheet"><b>{header}</b>{buttons.map((b,i)=><button key={i} type="button" className={b.role==='destructive'?'danger':''} onClick={()=>{b.handler?.();onDidDismiss?.()}}>{b.text}</button>)}</div></div>;
export const IonFab=({children})=><div className="ui-fab">{children}</div>; export const IonFabButton=({children,...p})=><button type="button" className="ui-fab-button" {...p}>{children}</button>;
